# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28e64cefa0fd0297ec8bbad95e17079bebfc115c489d64b4765f268078d16364fc303e4d4770bad0f97ff8ce5e4a56243cb979e2090700ae78e66b2bf0a88021

test:
  secret_key_base: 21523e98a6e88daeee5a41e83092c8d54d11d64218773fe54f099c15be7e94ced0f95089bea7164ee42e9fc993f946059a3cb73f9eb1c5171b95b8ee65966688

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
